### ISSUE TITLE
remove grid line and text

### ISSUE THREAD

**Issue by Foul-Tarnished** [Pear0533/ERMapGenerator#1]
Why is this not an option ?

I thought the main reason for this is to have a nice wallpaper or print or whatever

**Comment by Foul-Tarnished** [comment]
I was able to do it by commenting lines 206 to 221 in `ERMapGenerator.cs`

**Comment by Pear0533** [comment]
The purpose of this tool is to demonstrate how maps are assembled together for ELDEN RING specifically. It is not designed to generate assembled maps without annotations, because it wouldn't make sense: editing map tiles isn't supported in the program, so you would have to manually locate each tile, modify its texture, and then re-pack/re-generate all of the maps.

Again, feel free to implement map tile editing in the program if you wish, however I will not be doing so for the time being.

**Comment by Pear0533** [comment]
If you were able to figure out which lines should have been commented out, I'd recommend going in and adding the checkbox in yourself. Clearly you have some coding experience, so I would encourage you to take advantage of that and create a pull request for the feature you wish to have implemented.
